# Notes

* Scalatest offers a method called assertThrows to check if some code throws an exception, for example we could have written the following test:
   * assertThrows[IllegalArgumentException](userIdDecoder.decode("hello"))
* Documentation for [Self-type](https://docs.scala-lang.org/tour/self-types.html)
* How to capture this in [JavaScript](https://stackoverflow.com/questions/962033/what-underlies-this-javascript-idiom-var-self-this)

| Type         | GitHub link |
|--------------|-------------|
| Exercises    | [GenericFunctionExercises.scala](https://github.com/fp-tower/foundations/blob/master/exercises/src/main/scala/exercises/generic/GenericFunctionExercises.scala) |
| Tests        | [GenericFunctionExercisesTest.scala](https://github.com/fp-tower/foundations/blob/master/exercises/src/test/scala/exercises/generic/GenericFunctionExercisesTest.scala) |
| Answers      | [GenericFunctionAnswers.scala](https://github.com/fp-tower/foundations/blob/master/answers/src/main/scala/answers/generic/GenericFunctionAnswers.scala) |
| Test Answers | [GenericFunctionAnswersTest.scala](https://github.com/fp-tower/foundations/blob/master/answers/src/test/scala/answers/generic/GenericFunctionAnswersTest.scala) | 
